policies:
  - type: commit
    spec:
      headerLength: 72
      dco: true
      gpg: false
      imperative: true
      maximumOfOneCommit: true
      requireCommitBody: true
      conventional:
        types:
          - init
          - feat
          - module
          - style
          - fix
          - test
          - refact
        scopes:
          - policy
          - hot
          - update
          - config
